### ISSUE TITLE
cookie图片炸了(

### ISSUE THREAD

**Issue by LookStars** [Colter23/genshin-sign-mirai-plugin#10]
可能只有我遇到了这种问题?
![image](https://user-images.githubusercontent.com/79433682/186668573-526ce529-432e-438a-91af-0e8cba2076f1.png)

**Comment by LookStars** [comment]
虽然但是 不影响 但是还是要反馈一下

**Comment by Colter23** [comment]
最新版我应该把cookie图片直接打进jar包里了啊
