### ISSUE TITLE
cookie无法识别

### ISSUE THREAD

**Issue by Seayay** [Colter23/genshin-sign-mirai-plugin#12]
_MHYUUID=; UM_distinctid=; smidV2=; ltoken=; ltuid=; DEVICEFP_SEED_ID=; DEVICEFP_SEED_TIME=; DEVICEFP=; login_uid=; login_ticket=; CNZZDATA1275023096=; _ga=; _gid=; _gat=; .thumbcache_a5f2da7236017eb7e922ea0d742741d5=

cookie不大对呦, 再试试吧
如果要退出请回复  退出

**Comment by Colter23** [comment]
需要这两个字段 `cookie_token`  `account_id`

**Comment by LookStars** [comment]
> 需要这两个字段`cookie_token` `account_id`

`cookie_token_v2=; account_mid_v2=; ltoken_v2=; ltmid_v2=;`
问题：
无限重复成功签到该月一号，实际上并没有签到
尝试重新获取`cookie`：
然后`cookie`里只有上面那几个几个类似于你所说的,并没有找到你所说的(`cookie_token account_id`)
尝试解决：
使用`document.cookie`获取而非network里的ys，失败。
试过换游览器重新登录过，`cookie`值改变了，但是失败


要怎么处理，我感觉好像是我获取不到正常的`cookie`，通过控制台获取`document.cookie`也是没有用的.

`cookie`不大对呀，再试试吧
如果要退出请回复退出



我的issue格式可能有点烂，请不要介意
