### ISSUE TITLE
你好请问你有粉丝群吗？我不知道怎么启动私聊bot

### ISSUE THREAD

**Issue by sunshinemo** [Colter23/genshin-sign-mirai-plugin#2]
thanks

**Comment by Colter23** [comment]
没有粉丝群（
你会用mirai插件吗（
安好插件后对bot私聊发送 `原神签到` 就可以了，然后按照bot的指引

**Comment by m122469119** [comment]
能提供下0.33版本的源代码吗，git上的是0.31的源码，打出来的jar签到失败，直接使用0.33的jar倒是可以成功

**Comment by Colter23** [comment]
@m122469119  push了

**Comment by m122469119** [comment]
@Colter23 
蟹蟹大佬；
