### ISSUE TITLE
支持更多回复的自定义

### ISSUE THREAD

**Issue by KaRuichin** [Colter23/genshin-sign-mirai-plugin#3]
我这边很多群友反馈本插件自带`抓取cookie`的图片说明看不明白，所以我写了一个`Word文档`转成`PDF`丢到自己的网站上了，而`Edge`查看PDF又很方便。
因此请求支持更多回复的自定义。

**Comment by Colter23** [comment]
其实你可以把你的pdf截成图片，替换掉本插件数据目录 `data/top.colter.genshin-sign` 下的`cookie.png`图片     
自定义回复等我想想要不要加，要怎么加    
另外我感觉我写的获取cookie教程已经挺详细了（可以把你写的让我借鉴一下吗，如果好的话我可以修改一下我那个教程

**Comment by KaRuichin** [comment]
[抓取米游社cookie.pdf](https://github.com/Colter23/genshin-sign-mirai-plugin/files/8110972/cookie.pdf)
里面还嵌入了超链接所以才请求加入自定义回复（
而且图片放大就会模糊，过大会清楚但是不好发送以及查看。

**Comment by Colter23** [comment]
摸了几天鱼（[v0.3.4](https://github.com/Colter23/genshin-sign-mirai-plugin/releases/tag/v0.3.4)
