### ISSUE TITLE
插件启动失败

### ISSUE THREAD

**Issue by VatinaCharo** [Colter23/genshin-sign-mirai-plugin#6]
插件版本：0.3.5
mcl: 2.1.0-71ec418
mirai: 2.12.0

添加插件后，启动时报SSLHandshakeException，无法正常使用
如下为异常输出log
https://pastebin.com/TVwyf3y6

推测是第一次启动时没有cookie.png，而cookie.png的获取路径（https://img.colter.top/cookie.png）无法正常访问导致

**Comment by VatinaCharo** [comment]
log指出报异常的代码在PluginMain.kt的第50行

然后手动在浏览器里面访问了一下这个获取图片的地址，发现会被拦截

**Comment by VatinaCharo** [comment]
手动将cookie.png放入插件对应的data目录（.\data\top.colter.genshin-sign\）后，可以正常启动，所以估计就是这个问题

**Comment by Colter23** [comment]
0.3.6 修了
