### ISSUE TITLE
三蹦签到失败了

### ISSUE THREAD

**Issue by qq5520746** [Colter23/genshin-sign-mirai-plugin#8]
三蹦签到失败了

**Comment by it-kirito** [comment]
+1

**Comment by it-kirito** [comment]
看了一下，发现是签到链接换了。大佬有时间来更新一下吗=-=

**Comment by qq5520746** [comment]
> 看了一下，发现是签到链接换了。大佬有时间来更新一下吗=-=

等大佬

**Comment by KaRuichin** [comment]
隔壁喜佬的同类[项目](https://github.com/Hellobaka/GenshinSignBot)今天凌晨签到的时候还是正常的，大佬也许可以参考一下？

**Comment by Colter23** [comment]
草，这么多人用吗（修了 [v0.3.6](https://github.com/Colter23/genshin-sign-mirai-plugin/releases/tag/v0.3.6)

**Comment by qq5520746** [comment]
> 草，这么多人用吗（修了 [v0.3.6](https://github.com/Colter23/genshin-sign-mirai-plugin/releases/tag/v0.3.6)

抓到大佬
